# -*- coding: utf-8 -*-
"""stable_diffusion_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17fvNmltYnmnntxZsTZ-1Xih-03N6qbpA

# 🎨 Stable Diffusion From Scratch — MNIST Tutorial

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/)

> **⚡ Enable GPU first:** Runtime → Change runtime type → T4 GPU

---

## What you will learn

| Part | Topic |
|------|-------|
| 1 | **Noise Schedule** — linear β schedule, closed-form forward process |
| 2 | **U-Net Architecture** — ResBlocks, Self-Attention, Time Embeddings |
| 3 | **Dataset** — MNIST normalised to [-1, 1] |
| 4 | **Training Loop** — predicting added noise (DDPM objective) |
| 5 | **Sampling** — DDPM reverse process T → 0 |
| 6 | **Visualisations** — forward process, loss curve, generated samples |

### Core equations
$$q(x_t | x_0) = \sqrt{\bar{\alpha}_t}\, x_0 + \sqrt{1 - \bar{\alpha}_t}\, \varepsilon \qquad \varepsilon \sim \mathcal{N}(0, I)$$
$$\mathcal{L} = \mathbb{E}\left[\| \varepsilon - \hat{\varepsilon}_\theta(x_t, t) \|^2\right]$$

## ⚙️ Setup
"""

# All packages are pre-installed in Colab — just verify
import torch
print(f"PyTorch version : {torch.__version__}")
print(f"CUDA available  : {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU             : {torch.cuda.get_device_name(0)}")
else:
    print("⚠️  No GPU detected. Go to Runtime → Change runtime type → T4 GPU")

import math
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm   # notebook-friendly progress bar

print("✅ All imports successful")

# ─────────────────────────────────────────────
#  HYPERPARAMETERS  (tuned for fast Colab training)
# ─────────────────────────────────────────────
IMG_SIZE   = 28      # MNIST images are 28×28
CHANNELS   = 1       # grayscale
BATCH_SIZE = 128
EPOCHS     = 30      # ~5 min on T4; increase to 30 for sharper results
LR         = 3e-4
T          = 300     # total diffusion timesteps
DEVICE     = "cuda" if torch.cuda.is_available() else "cpu"

print(f"Device  : {DEVICE}")
print(f"Epochs  : {EPOCHS}")
print(f"T steps : {T}")

"""---
## Part 1 — Noise Schedule

The **β schedule** controls how quickly noise is added. We use the linear schedule from Ho et al. (2020):

$$\beta_1 = 10^{-4} \;\to\; \beta_T = 0.02 \quad \text{(linearly spaced)}$$

From β we derive $\bar{\alpha}_t = \prod_{s=1}^{t}(1-\beta_s)$, which lets us sample *any* noisy image directly:

$$x_t = \sqrt{\bar{\alpha}_t}\, x_0 + \sqrt{1-\bar{\alpha}_t}\, \varepsilon$$
"""

class NoiseSchedule:
    """
    Linear β noise schedule.

    Key quantities:
      betas        β_t  — noise variance added at step t
      alphas       α_t = 1 - β_t
      alpha_bars   ᾱ_t = ∏ α_s  (cumulative product)
    """
    def __init__(self, T: int, beta_start=1e-4, beta_end=0.02):
        self.T = T
        self.betas            = torch.linspace(beta_start, beta_end, T).to(DEVICE)
        self.alphas           = 1.0 - self.betas
        self.alpha_bars       = torch.cumprod(self.alphas, dim=0)
        self.sqrt_alpha_bars  = torch.sqrt(self.alpha_bars)
        self.sqrt_one_minus_ab = torch.sqrt(1.0 - self.alpha_bars)
        self.sqrt_recip_alpha  = torch.sqrt(1.0 / self.alphas)

    def q_sample(self, x0: torch.Tensor, t: torch.Tensor):
        """
        Forward process — add noise to x0 at timestep t.
        Returns (x_noisy, noise).
        """
        noise       = torch.randn_like(x0)
        sqrt_ab     = self.sqrt_alpha_bars[t].view(-1, 1, 1, 1)
        sqrt_one_ab = self.sqrt_one_minus_ab[t].view(-1, 1, 1, 1)
        x_noisy     = sqrt_ab * x0 + sqrt_one_ab * noise
        return x_noisy, noise

schedule = NoiseSchedule(T)
print("✅ Noise schedule created")
print(f"   β range  : {schedule.betas[0].item():.5f} → {schedule.betas[-1].item():.4f}")
print(f"   ᾱ range  : {schedule.alpha_bars[0].item():.4f} → {schedule.alpha_bars[-1].item():.6f}")

"""---
## Part 2 — U-Net Architecture

The denoiser is a **U-Net** with three key ingredients:

1. **Sinusoidal Time Embedding** — encodes scalar `t` into a rich vector (same idea as Transformer positional encoding)
2. **ResBlock** — convolutional block that *injects* the time embedding so the network knows how noisy the input is
3. **Self-Attention** — at the bottleneck, every pixel can attend to every other pixel for global coherence
4. **Skip connections** — encoder features are concatenated into the decoder, preserving fine spatial detail
"""

# ── 2a. Sinusoidal Time Embedding ──────────────────────────────────────────
class SinusoidalTimeEmbedding(nn.Module):
    """
    Encodes scalar timestep t → dense vector.
    Uses sin/cos at different frequencies, then passes through MLP.

    Why needed: the U-Net must behave differently at t=1 (barely noisy)
    vs t=299 (nearly pure noise).
    """
    def __init__(self, dim: int):
        super().__init__()
        self.dim = dim
        self.mlp = nn.Sequential(
            nn.Linear(dim, dim * 4),
            nn.SiLU(),            # Swish: smoother than ReLU
            nn.Linear(dim * 4, dim),
        )

    def forward(self, t: torch.Tensor) -> torch.Tensor:
        half  = self.dim // 2
        freqs = torch.exp(
            -math.log(10000) * torch.arange(half, device=t.device) / (half - 1)
        )
        args  = t[:, None].float() * freqs[None, :]
        emb   = torch.cat([torch.sin(args), torch.cos(args)], dim=-1)
        return self.mlp(emb)

print("✅ SinusoidalTimeEmbedding defined")

# Quick test
_emb = SinusoidalTimeEmbedding(128).to(DEVICE)
_t   = torch.randint(0, T, (4,), device=DEVICE)
print(f"   t shape    : {_t.shape}")
print(f"   emb shape  : {_emb(_t).shape}  (batch=4, dim=128)")

# ── 2b. ResBlock ───────────────────────────────────────────────────────────
class ResBlock(nn.Module):
    """
    Residual block with time injection.

    Flow: x → Norm → Conv → SiLU → (+t_emb) → Norm → Conv → (+skip)

    Time embedding is projected to (out_ch,) and broadcast-added
    over the spatial dimensions, giving direct control over noise level.
    """
    def __init__(self, in_ch: int, out_ch: int, time_dim: int):
        super().__init__()
        self.norm1     = nn.GroupNorm(8, in_ch)
        self.conv1     = nn.Conv2d(in_ch, out_ch, 3, padding=1)
        self.norm2     = nn.GroupNorm(8, out_ch)
        self.conv2     = nn.Conv2d(out_ch, out_ch, 3, padding=1)
        self.time_proj = nn.Linear(time_dim, out_ch)     # ← inject t here
        self.skip      = nn.Conv2d(in_ch, out_ch, 1) if in_ch != out_ch else nn.Identity()

    def forward(self, x: torch.Tensor, t_emb: torch.Tensor) -> torch.Tensor:
        h = self.conv1(F.silu(self.norm1(x)))
        h = h + self.time_proj(F.silu(t_emb))[:, :, None, None]  # broadcast over H,W
        h = self.conv2(F.silu(self.norm2(h)))
        return h + self.skip(x)

print("✅ ResBlock defined")

# ── 2c. Self-Attention ─────────────────────────────────────────────────────
class SelfAttention(nn.Module):
    """
    Spatial self-attention at the bottleneck (7×7 feature map).
    Lets every spatial position attend to every other — essential
    for global coherence (e.g. consistent digit shape).
    """
    def __init__(self, channels: int):
        super().__init__()
        self.norm = nn.GroupNorm(8, channels)
        self.qkv  = nn.Conv2d(channels, channels * 3, 1)
        self.proj = nn.Conv2d(channels, channels, 1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        B, C, H, W = x.shape
        h   = self.norm(x)
        qkv = self.qkv(h).reshape(B, 3, C, H * W).permute(1, 0, 2, 3)
        q, k, v = qkv[0], qkv[1], qkv[2]
        # Scaled dot-product attention
        attn = torch.softmax(q.transpose(-1,-2) @ k * (C ** -0.5), dim=-1)
        out  = (attn @ v.transpose(-1,-2)).transpose(-1,-2)
        out  = out.reshape(B, C, H, W)
        return x + self.proj(out)   # residual

print("✅ SelfAttention defined")

# ── 2d. Full U-Net ─────────────────────────────────────────────────────────
class UNet(nn.Module):
    """
    Mini U-Net denoiser for 28×28 images.

    Input  : (B, 1, 28, 28) noisy image  +  (B,) timestep t
    Output : (B, 1, 28, 28) predicted noise ε̂

    Spatial resolution:
      Encoder  :  28 → 14 → 7
      Bottleneck:  7  (with self-attention)
      Decoder  :   7 → 14 → 28  (+ skip connections from encoder)
    """
    def __init__(self, img_channels=1, base_dim=64, time_dim=128):
        super().__init__()
        self.time_mlp = SinusoidalTimeEmbedding(time_dim)

        # ── Encoder ──────────────────────────────────────────────────────
        self.enc_in   = nn.Conv2d(img_channels, base_dim, 3, padding=1)
        self.enc_res1 = ResBlock(base_dim,      base_dim,     time_dim)
        self.down1    = nn.Conv2d(base_dim,     base_dim * 2, 4, 2, 1)   # 28 → 14
        self.enc_res2 = ResBlock(base_dim * 2,  base_dim * 2, time_dim)
        self.down2    = nn.Conv2d(base_dim * 2, base_dim * 4, 4, 2, 1)   # 14 → 7

        # ── Bottleneck ────────────────────────────────────────────────────
        self.bot_res1 = ResBlock(base_dim * 4, base_dim * 4, time_dim)
        self.bot_attn = SelfAttention(base_dim * 4)
        self.bot_res2 = ResBlock(base_dim * 4, base_dim * 4, time_dim)

        # ── Decoder  (note: *2 channels due to skip concat) ───────────────
        self.up2      = nn.ConvTranspose2d(base_dim * 4, base_dim * 2, 4, 2, 1)  # 7 → 14
        self.dec_res2 = ResBlock(base_dim * 4, base_dim * 2, time_dim)  # *4: skip
        self.up1      = nn.ConvTranspose2d(base_dim * 2, base_dim,     4, 2, 1)  # 14 → 28
        self.dec_res1 = ResBlock(base_dim * 2, base_dim,     time_dim)  # *2: skip

        # ── Output ────────────────────────────────────────────────────────
        self.out_norm = nn.GroupNorm(8, base_dim)
        self.out_conv = nn.Conv2d(base_dim, img_channels, 1)

    def forward(self, x: torch.Tensor, t: torch.Tensor) -> torch.Tensor:
        t_emb = self.time_mlp(t)                           # (B, time_dim)

        # Encoder
        x1 = self.enc_res1(self.enc_in(x),  t_emb)        # (B, 64,  28, 28)
        x2 = self.enc_res2(self.down1(x1),  t_emb)        # (B, 128, 14, 14)
        x3 = self.down2(x2)                                # (B, 256,  7,  7)

        # Bottleneck
        x3 = self.bot_res1(x3, t_emb)
        x3 = self.bot_attn(x3)
        x3 = self.bot_res2(x3, t_emb)

        # Decoder (concatenate skip connections)
        x  = self.dec_res2(torch.cat([self.up2(x3), x2], dim=1), t_emb)
        x  = self.dec_res1(torch.cat([self.up1(x),  x1], dim=1), t_emb)

        return self.out_conv(F.silu(self.out_norm(x)))


# Build model and print summary
model = UNet(img_channels=CHANNELS).to(DEVICE)

total     = sum(p.numel() for p in model.parameters())
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"✅ U-Net created")
print(f"   Parameters : {total:,} total  |  {trainable:,} trainable")
print(f"   Memory (fp32) ≈ {total*4/1024**2:.1f} MB")

# Verify forward pass shapes
with torch.no_grad():
    _x = torch.randn(2, CHANNELS, IMG_SIZE, IMG_SIZE, device=DEVICE)
    _t = torch.randint(0, T, (2,), device=DEVICE)
    _o = model(_x, _t)
print(f"   Input  shape : {list(_x.shape)}")
print(f"   Output shape : {list(_o.shape)}  ✓")

"""---
## Part 3 — Dataset (MNIST)

We normalise pixels from `[0, 1]` → `[-1, 1]`.  
This matters because the diffusion endpoint $x_T \sim \mathcal{N}(0, I)$ has values centred at 0 — matching the data range makes learning easier.
"""

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,)),   # [0,1] → [-1,1]
])

dataset = datasets.MNIST("./data", train=True, download=True, transform=transform)
loader  = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True,
                     num_workers=2, pin_memory=True)

print(f"✅ MNIST loaded: {len(dataset):,} images")
print(f"   Batches per epoch: {len(loader)}")

# Peek at a batch
sample_imgs, sample_labels = next(iter(loader))
print(f"   Batch shape : {sample_imgs.shape}")
print(f"   Value range : [{sample_imgs.min():.2f}, {sample_imgs.max():.2f}]")

# Show 8 real images
fig, axes = plt.subplots(1, 8, figsize=(12, 2))
for i, ax in enumerate(axes):
    ax.imshow((sample_imgs[i].squeeze() + 1) / 2, cmap='gray', vmin=0, vmax=1)
    ax.set_title(str(sample_labels[i].item()), fontsize=10)
    ax.axis('off')
plt.suptitle("Real MNIST samples (normalised to [-1,1], displayed as [0,1])", y=1.02)
plt.tight_layout()
plt.show()

"""---
## Part 4 — Forward Process Visualisation

Before training, let's *see* what the forward process does — adding more noise at each timestep.
"""

def show_forward_process(schedule, img_tensor):
    """Visualise one image being progressively noised."""
    timesteps = [0, 30, 60, 100, 150, 200, 250, T-1]
    fig, axes = plt.subplots(1, len(timesteps), figsize=(14, 2.5))
    fig.suptitle("Forward diffusion: clean image → pure noise", fontsize=12, y=1.02)

    img = img_tensor.unsqueeze(0).to(DEVICE)
    for ax, t_val in zip(axes, timesteps):
        t_tensor = torch.tensor([t_val], device=DEVICE)
        noisy, _ = schedule.q_sample(img, t_tensor)
        noisy_np = (noisy.squeeze().cpu().clamp(-1, 1) + 1) / 2
        ax.imshow(noisy_np, cmap='gray', vmin=0, vmax=1)
        ax.set_title(f"t={t_val}", fontsize=9)
        ax.axis('off')
    plt.tight_layout()
    plt.show()

show_forward_process(schedule, sample_imgs[0])

# Also visualise the ᾱ schedule — how much signal remains at each t
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 3.5))

ts = range(T)
ax1.plot(ts, schedule.betas.cpu().numpy(), color='#E24B4A', linewidth=1.5)
ax1.set_title("β_t (noise variance added at step t)")
ax1.set_xlabel("timestep t")
ax1.grid(alpha=0.3)

ax2.plot(ts, schedule.alpha_bars.cpu().numpy(), color='#534AB7', linewidth=1.5)
ax2.set_title("ᾱ_t (signal retained — cumulative)")
ax2.set_xlabel("timestep t")
ax2.grid(alpha=0.3)

plt.tight_layout()
plt.show()
print("When ᾱ_t → 0, the image is essentially pure noise.")

"""---
## Part 5 — Training Loop

**DDPM training algorithm** (Algorithm 1, Ho et al. 2020) — surprisingly simple:

```
for each batch:
  1. Sample random t ~ Uniform(0, T)
  2. Sample ε ~ N(0, I)
  3. Compute x_t = √ᾱ_t · x₀ + √(1-ᾱ_t) · ε       ← closed form!
  4. Predict ε̂ = U-Net(x_t, t)
  5. Loss = MSE(ε, ε̂)
  6. Backprop + Adam step
```
"""

def train(model, schedule, loader):
    optimizer  = torch.optim.Adam(model.parameters(), lr=LR)
    epoch_losses = []

    for epoch in range(EPOCHS):
        running_loss = 0.0
        pbar = tqdm(loader, desc=f"Epoch {epoch+1}/{EPOCHS}", leave=True)

        for images, _ in pbar:
            images = images.to(DEVICE)                         # (B,1,28,28)
            B      = images.shape[0]

            # Step 1: random timestep per image
            t = torch.randint(0, T, (B,), device=DEVICE)

            # Steps 2 & 3: add noise (closed form — no loop needed!)
            x_noisy, noise = schedule.q_sample(images, t)

            # Step 4: predict the noise
            pred_noise = model(x_noisy, t)

            # Step 5: MSE loss
            loss = F.mse_loss(pred_noise, noise)

            # Step 6: optimise
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            running_loss += loss.item()
            pbar.set_postfix(loss=f"{loss.item():.4f}")

        avg = running_loss / len(loader)
        epoch_losses.append(avg)
        print(f"  Epoch {epoch+1:02d}/{EPOCHS} — avg loss: {avg:.4f}")

    return epoch_losses


print("Starting training...\n")
losses = train(model, schedule, loader)

# Save checkpoint
torch.save(model.state_dict(), "unet_mnist.pth")
print("\n✅ Training complete! Checkpoint saved as unet_mnist.pth")

# Plot training loss
plt.figure(figsize=(7, 4))
plt.plot(range(1, EPOCHS+1), losses, marker='o', color='#534AB7', linewidth=2, markersize=5)
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.title("Training loss — noise prediction MSE")
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""---
## Part 6 — Sampling (Reverse Process)

**DDPM sampling algorithm** (Algorithm 2, Ho et al. 2020):

Start from $x_T \sim \mathcal{N}(0, I)$, then iterate **T → 1**:

$$x_{t-1} = \frac{1}{\sqrt{\alpha_t}} \left( x_t - \frac{\beta_t}{\sqrt{1-\bar{\alpha}_t}} \hat{\varepsilon}_\theta(x_t, t) \right) + \sqrt{\beta_t}\, z \qquad z \sim \mathcal{N}(0, I)$$

> This takes ~300 steps. After training more epochs (30+), digits become much sharper.
"""

@torch.no_grad()
def sample_ddpm(model, schedule, n_samples=16):
    """Generate images by running the reverse diffusion process T → 0."""
    model.eval()
    # Start from pure Gaussian noise
    x = torch.randn(n_samples, CHANNELS, IMG_SIZE, IMG_SIZE, device=DEVICE)

    for t_idx in tqdm(reversed(range(T)), desc="Sampling", total=T, leave=True):
        t = torch.full((n_samples,), t_idx, device=DEVICE, dtype=torch.long)

        pred_noise   = model(x, t)
        alpha        = schedule.alphas[t_idx]
        beta         = schedule.betas[t_idx]
        sqrt_recip   = schedule.sqrt_recip_alpha[t_idx]
        sqrt_one_ab  = schedule.sqrt_one_minus_ab[t_idx]

        # Compute posterior mean
        x = sqrt_recip * (x - (beta / sqrt_one_ab) * pred_noise)

        # Add noise for all steps except the last
        if t_idx > 0:
            x = x + torch.sqrt(beta) * torch.randn_like(x)

    model.train()
    return x.cpu()


print("Generating 16 samples...")
samples = sample_ddpm(model, schedule, n_samples=16)
print(f"✅ Generated samples shape: {samples.shape}")

# Display 4×4 grid of generated samples
fig, axes = plt.subplots(4, 4, figsize=(8, 8))
fig.suptitle("Generated digits — DDPM sampling (train more epochs for better quality)",
             fontsize=11, y=1.01)
for i, ax in enumerate(axes.flat):
    img = (samples[i].squeeze().clamp(-1, 1) + 1) / 2
    ax.imshow(img, cmap='gray', vmin=0, vmax=1)
    ax.axis('off')
plt.tight_layout()
plt.show()

"""---
## Part 7 — Denoising Trajectory

Watch a single image emerge from noise — snapshots every ~50 reverse steps.
"""

@torch.no_grad()
def show_denoising_trajectory(model, schedule):
    model.eval()
    capture_at = set(range(0, T, T // 7)) | {0}   # ~8 snapshots
    snapshots, step_labels = [], []

    x = torch.randn(1, CHANNELS, IMG_SIZE, IMG_SIZE, device=DEVICE)

    for t_idx in tqdm(reversed(range(T)), desc="Trajectory", total=T, leave=False):
        t = torch.full((1,), t_idx, device=DEVICE, dtype=torch.long)
        pred_noise  = model(x, t)
        beta        = schedule.betas[t_idx]
        sqrt_recip  = schedule.sqrt_recip_alpha[t_idx]
        sqrt_one_ab = schedule.sqrt_one_minus_ab[t_idx]

        x = sqrt_recip * (x - (beta / sqrt_one_ab) * pred_noise)
        if t_idx > 0:
            x = x + torch.sqrt(beta) * torch.randn_like(x)

        if t_idx in capture_at:
            snapshots.append(x.cpu().squeeze().clamp(-1, 1).numpy())
            step_labels.append(f"t={t_idx}")

    model.train()
    # Show in reverse (noise → image)
    snapshots   = snapshots[::-1]
    step_labels = step_labels[::-1]

    fig, axes = plt.subplots(1, len(snapshots), figsize=(15, 2.5))
    fig.suptitle("Denoising trajectory: pure noise → generated image", fontsize=12, y=1.02)
    for ax, img, lbl in zip(axes, snapshots, step_labels):
        ax.imshow((img + 1) / 2, cmap='gray', vmin=0, vmax=1)
        ax.set_title(lbl, fontsize=9)
        ax.axis('off')
    plt.tight_layout()
    plt.show()

show_denoising_trajectory(model, schedule)

"""---
## 🎯 Bonus — Load Saved Model & Generate More
"""

# Load the saved checkpoint (useful after restarting the runtime)
model_loaded = UNet(img_channels=CHANNELS).to(DEVICE)
model_loaded.load_state_dict(torch.load("unet_mnist.pth", map_location=DEVICE))
model_loaded.eval()
print("✅ Model loaded from checkpoint")

# Generate a larger batch
new_samples = sample_ddpm(model_loaded, schedule, n_samples=16)

fig, axes = plt.subplots(4, 4, figsize=(8, 8))
for i, ax in enumerate(axes.flat):
    ax.imshow((new_samples[i].squeeze().clamp(-1,1)+1)/2, cmap='gray', vmin=0, vmax=1)
    ax.axis('off')
plt.suptitle("Freshly generated samples from saved model", y=1.01)
plt.tight_layout()
plt.show()